version: '3.8'

volumes:
  pgdata:
  redis_data:

services:

  db:
    image: postgres:alpine
    container_name: tensor-postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: $DB_LOGIN
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
#      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: /var/lib/postgresql/data/bot
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - tensor_network
#    network_mode: "host"

  redis:
    image: redis:alpine
    container_name: tensor-redis
    restart: always
    networks:
      - tensor_network
    volumes:
      - redis_data:/data
    ports:
      - "6376:6379"

  tensor:
    container_name: tensor
    build:
      context: .
    # command: bash -c "alembic revision --autogenerate -m "First" && alembic stamp head && alembic upgrade head && python aiobot.py"
    restart: always
    networks:
      - tensor_network
    env_file:
      - .env
    depends_on:
      - db
      - redis
    logging:
      options:
        max-size: "10m"
        max-file: "5"

networks:
  tensor_network: